name: Build RustDesk Native Client

on:
  workflow_dispatch:
    inputs:
      os:
        description: 'Target OS'
        required: true
        default: 'windows'
        type: choice
        options:
          - windows
          - linux
          - macos

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - os: windows
            runner: windows-latest
          - os: linux
            runner: ubuntu-latest
          - os: macos
            runner: macos-latest

    if: github.event.inputs.os == matrix.os

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build RustDesk (Release)
        run: cargo build --release

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-${{ matrix.os }}
          path: |
            target/release/rustdesk*
          retention-days: 7
