jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install vcpkg
        shell: powershell
        run: |
          git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          # 安装 opus 库，magnum-opus 依赖它
          C:\vcpkg\vcpkg.exe install opus:x64-windows
          echo "VCPKG_ROOT=C:\\vcpkg" >> $env:GITHUB_ENV

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build RustDesk (Release)
        run: cargo build --release --bin rustdesk

      - name: Upload RustDesk EXE
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: target/release/rustdesk.exe
          retention-days: 7
