name: Build RustDesk Windows Client with Custom Server

on:
  workflow_dispatch:
    inputs:
      server:       # rendezvous server IP or domain
        description: 'RustDesk Rendezvous Server (e.g. 1.2.3.4)'
        required: true
      key:
        description: 'Server key (e.g. XXX@YYYY)'
        required: true

jobs:
  build:
    name: Build for Windows
    runs-on: windows-latest

    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - name: 🧾 Checkout Source with Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: 🦀 Install Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: 📦 Install vcpkg and dependencies
        shell: powershell
        run: |
          if (!(Test-Path "$env:VCPKG_ROOT")) {
            git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
            cd $env:VCPKG_ROOT
            .\bootstrap-vcpkg.bat
          }
          cd $env:GITHUB_WORKSPACE
          $env:Path += ";$env:VCPKG_ROOT"
          vcpkg install opus:x64-windows-static openssl:x64-windows-static libvpx:x64-windows-static

      - name: 🔧 Inject Rendezvous Server and Key
        shell: powershell
        run: |
          $settingsPath = Join-Path $env:GITHUB_WORKSPACE "src-tauri\settings.toml"
          if (!(Test-Path $settingsPath)) {
            Write-Error "❌ 找不到 settings.toml: $settingsPath"
            exit 1
          }
          (Get-Content $settingsPath) -replace 'rendezvous_server\s*=\s*".*?"', 'rendezvous_server = "${{ github.event.inputs.server }}"' |
            Set-Content $settingsPath
          (Get-Content $settingsPath) -replace 'key\s*=\s*".*?"', 'key = "${{ github.event.inputs.key }}"' |
            Set-Content $settingsPath

      - name: 🛠️ Build rustdesk.exe
        run: cargo build --release --bin rustdesk

      - name: 📤 Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-custom
          path: target/release/rustdesk.exe
