name: Build RustDesk Windows Client with Custom Server

on:
  workflow_dispatch:
    inputs:
      server:       # rendezvous server
        description: 'Server domain or IP (e.g., 1.2.3.4:21117)'
        required: true
      key:
        description: 'Key for server (e.g., JSZCB@2025)'
        required: true

jobs:
  build:
    name: Build Windows Client
    runs-on: windows-latest

    env:
      VCPKG_ROOT: C:\vcpkg

    steps:
      - name: Checkout Source with Submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Rust Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install vcpkg dependencies
        shell: powershell
        run: |
          if (!(Test-Path "$env:VCPKG_ROOT")) {
            git clone https://github.com/microsoft/vcpkg.git $env:VCPKG_ROOT
            cd $env:VCPKG_ROOT
            .\bootstrap-vcpkg.bat
          }
          cd $env:GITHUB_WORKSPACE
          $env:Path += ";$env:VCPKG_ROOT"
          $env:VCPKG_DEFAULT_TRIPLET = "x64-windows"
          vcpkg install

      - name: Inject Server Info into Source
        shell: powershell
        run: |
          $file = "$env:GITHUB_WORKSPACE\libs\hbb_common\src\config.rs"
          (Get-Content $file) -replace '"rendezvous.rustdesk.com:\d+"', '"${{ github.event.inputs.server }}"' | Set-Content $file
          (Get-Content $file) -replace '"rustdesk-key"', '"${{ github.event.inputs.key }}"' | Set-Content $file

      - name: Build RustDesk Executable
        run: cargo build --release --bin rustdesk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows-custom
          path: target/release/rustdesk.exe
