name: Build RustDesk Windows Client

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build RustDesk (Release)
        run: cargo build --release --bin rustdesk

      - name: Upload RustDesk EXE
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: |
            target/release/rustdesk.exe
          retention-days: 7
