name: Build RustDesk Custom Client

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target OS'
        required: true
        default: 'windows'
        type: choice
        options:
          - windows
          - linux
          - macos

env:
  RENDEZVOUS_SERVER: ${{ secrets.RENDEZVOUS_SERVER }}
  RELAY_SERVER: ${{ secrets.RELAY_SERVER }}
  RS_PUB_KEY: ${{ secrets.RS_PUB_KEY }}

jobs:
  build-windows:
    if: ${{ github.event.inputs.target == 'windows' }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install -g pnpm
          pnpm install

      - name: Install Tauri CLI
        run: pnpm dlx @tauri-apps/cli install

      - name: Build Tauri App (Windows)
        run: pnpm tauri build

      - uses: actions/upload-artifact@v3
        with:
          name: rustdesk-windows
          path: |
            src-tauri/target/release/bundle

  build-linux:
    if: ${{ github.event.inputs.target == 'linux' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libwebkit2gtk-4.0-dev build-essential curl wget libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          npm install -g pnpm
          pnpm install

      - name: Install Tauri CLI
        run: pnpm dlx @tauri-apps/cli install

      - name: Build Tauri App (Linux)
        run: pnpm tauri build

      - uses: actions/upload-artifact@v3
        with:
          name: rustdesk-linux
          path: |
            src-tauri/target/release/bundle

  build-macos:
    if: ${{ github.event.inputs.target == 'macos' }}
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          brew install webkit2gtk gtk+3 cairo gobject-introspection
          npm install -g pnpm
          pnpm install

      - name: Install Tauri CLI
        run: pnpm dlx @tauri-apps/cli install

      - name: Build Tauri App (macOS)
        run: pnpm tauri build

      - uses: actions/upload-artifact@v3
        with:
          name: rustdesk-macos
          path: |
            src-tauri/target/release/bundle
