name: Build RustDesk Windows Client

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source with submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install vcpkg and dependencies
        shell: powershell
        run: |
          if (!(Test-Path "C:\vcpkg")) {
            git clone https://github.com/microsoft/vcpkg.git C:\vcpkg
            cd C:\vcpkg
            .\bootstrap-vcpkg.bat
          }
          cd D:\a\rustdesk\rustdesk
          C:\vcpkg\vcpkg.exe install
        env:
          VCPKG_ROOT: C:\vcpkg

      - name: Build RustDesk (Release)
        run: cargo build --release --bin rustdesk
        working-directory: D:\a\rustdesk\rustdesk

      - name: Upload RustDesk EXE
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: D:\a\rustdesk\rustdesk\target\release\rustdesk.exe
