name: Build RustDesk Windows Client with Custom Server

on:
  workflow_dispatch:
    inputs:
      server:
        description: 'Server domain or IP'
        required: true
      key:
        description: 'Key for server'
        required: true

jobs:
  build:
    runs-on: windows-latest

    env:
      VCPKG_ROOT: C:\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows-static

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install vcpkg and Dependencies
        shell: powershell
        run: |
          if (!(Test-Path "$env:VCPKG_ROOT\vcpkg.exe")) {
            git clone https://github.com/microsoft/vcpkg $env:VCPKG_ROOT
            cd $env:VCPKG_ROOT
            .\bootstrap-vcpkg.bat
          }
          cd $env:GITHUB_WORKSPACE
          Copy-Item .\vcpkg-configuration.json .\vcpkg.json
          & "$env:VCPKG_ROOT\vcpkg.exe" install

      - name: Inject Custom Server
        shell: powershell
        run: |
          $settingsPath = "${{ github.workspace }}\src-tauri\settings.toml"
          (Get-Content $settingsPath) -replace 'rendezvous_server\s*=\s*".*?"', 'rendezvous_server = "${{ github.event.inputs.server }}"' | Set-Content $settingsPath
          (Get-Content $settingsPath) -replace 'key\s*=\s*".*?"', 'key = "${{ github.event.inputs.key }}"' | Set-Content $settingsPath

      - name: Build Windows Client
        run: cargo build --release --bin rustdesk

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-windows
          path: target/release/rustdesk.exe
